### ISSUE TITLE
enable gateway host network mode

### ISSUE THREAD

**Issue by dulmandakh** [canonical/k8s-snap#1099]
#### Summary

Since Cilium 1.16, it supports gateway host network mode which allows to bind gateway to host network without load balancer service. See https://docs.cilium.io/en/latest/network/servicemesh/gateway-api/gateway-api/#host-network-mode

#### Why is this important?

It's very useful feature for single node clusters where IP might be scarce and users don't need to configure load balancer. Microk8s' ingress offers similar feature.

#### Are you interested in contributing to this feature?
No, I don't know go programming language.

**Comment by dulmandakh** [comment]
ingress has similar feature https://docs.cilium.io/en/latest/network/servicemesh/ingress/#host-network-mode

**Comment by dulmandakh** [comment]
I was able to make it work with following changes

Change following values to true in `cilium-config`

```yaml
envoy-keep-cap-netbindservice: "true"
gateway-api-hostnetwork-enabled: "true"
```

Add `NET_BIND_SERVICE` to cilium-agent container capabilities, then restart cilium and cilium-operator pods.

Following gateway won't try to start LoadBalancer, and just work

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: my-gateway
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name: web-gw
    allowedRoutes:
      namespaces:
        from: Same

```
