### ISSUE TITLE
Resizing of PV/PVC fails  - failed to pull and unpack image "ghcr.io/canonical/rawfile-localpv:None"

### ISSUE THREAD

**Issue by nobuto-m** [canonical/k8s-snap#1278]
### Summary

As per the tutorial, the k8s snap enabled a local PV backend out of the box.
https://documentation.ubuntu.com/canonical-kubernetes/latest/snap/tutorial/getting-started/

However, the resize of a PVC/PV fails. Resizing is somewhat critical for operational phases. Let's say somebody deployed a database (MySQL, PostgreSQL, etc.) and after some time, they might want to extend the persistent volume as the database grows but it's going to be blocked by the underlying k8s.

### What Should Happen Instead?

Resizing works and completes without an error.

### Reproduction Steps

1. Prepare a VM with Ubuntu 24.04 LTS
2. Install k8s snap as per the tutorial.
   ```bash
   $ sudo snap install k8s --classic --channel=1.32-classic/stable

   $ snap list k8s
   Name  Version  Rev   Tracking             Publisher   Notes
   k8s   v1.32.2  2717  1.32-classic/stable  canonical✓  classic


   $ sudo k8s bootstrap

   $ sudo k8s status --wait-ready
   cluster status:           ready
   control plane nodes:      192.168.122.26:6400 (voter)
   high availability:        no
   datastore:                k8s-dqlite
   network:                  enabled
   dns:                      enabled at 10.152.183.247
   ingress:                  disabled
   load-balancer:            disabled
   local-storage:            enabled at /var/snap/k8s/common/rawfile-storage
   gateway                   enabled

   $ sudo k8s kubectl get sc
   NAME                            PROVISIONER              RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
   csi-rawfile-default (default)   rawfile.csi.openebs.io   Delete          WaitForFirstConsumer   true                   108s
   ```
   **-> `ALLOWVOLUMEEXPANSION` is true**
 
3. Create a pod with a PVC as per the tutorial
   ```bash
   sudo k8s kubectl apply -f https://raw.githubusercontent.com/canonical/k8s-snap/main/docs/canonicalk8s/assets/tutorial-pod-with-pvc.yaml
   ```

4. Resize the PVC.
   ```bash
   sudo k8s kubectl patch pvc/myclaim -p '{"spec":{"resources":{"requests":{"storage":"2Gi"}}}}'
   ```
5. Resizing step starts, but never completes.

```bash
$ sudo k8s kubectl describe pvc
Name:          myclaim
Namespace:     default
StorageClass:  csi-rawfile-default
Status:        Bound
Volume:        pvc-424555d3-16c1-4a5e-bd3f-3181268e0244
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: rawfile.csi.openebs.io
               volume.kubernetes.io/selected-node: k8s-test
               volume.kubernetes.io/storage-provisioner: rawfile.csi.openebs.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       storage-writer-pod
Conditions:
  Type       Status  LastProbeTime                     LastTransitionTime                Reason  Message
  ----       ------  -----------------                 ------------------                ------  -------
  Resizing   True    Mon, 01 Jan 0001 00:00:00 +0000   Mon, 07 Apr 2025 09:07:24 +0000           
Events:
  Type     Reason                 Age               From                                                                                           Message
  ----     ------                 ----              ----                                                                                           -------
  Normal   WaitForFirstConsumer   43s               persistentvolume-controller                                                                    waiting for first consumer to be created before binding
  Normal   ExternalProvisioning   43s               persistentvolume-controller                                                                    Waiting for a volume to be created either by the external provisioner 'rawfile.csi.openebs.io' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
  Normal   Provisioning           36s               rawfile.csi.openebs.io_ck-storage-rawfile-csi-node-tvkt2_d31fed9e-b0c7-47bf-bb96-366a7cead49e  External provisioner is provisioning volume for claim "default/myclaim"
  Normal   ProvisioningSucceeded  36s               rawfile.csi.openebs.io_ck-storage-rawfile-csi-node-tvkt2_d31fed9e-b0c7-47bf-bb96-366a7cead49e  Successfully provisioned volume pvc-424555d3-16c1-4a5e-bd3f-3181268e0244
  Normal   ExternalExpanding      15s               volume_expand                                                                                  waiting for an external controller to expand this PVC
  Normal   Resizing               4s (x2 over 14s)  external-resizer rawfile.csi.openebs.io                                                        External resizer is resizing volume pvc-424555d3-16c1-4a5e-bd3f-3181268e0244
  Warning  VolumeResizeFailed     4s                external-resizer rawfile.csi.openebs.io                                                        resize volume "pvc-424555d3-16c1-4a5e-bd3f-3181268e0244" by resizer "rawfile.csi.openebs.io" failed: rpc error: code = DeadlineExceeded desc = Deadline Exceeded
```
**-> `Deadline Exceeded`**

```bash
$ sudo k8s kubectl get pod -A
NAMESPACE     NAME                                        READY   STATUS              RESTARTS   AGE
default       storage-writer-pod                          1/1     Running             0          119s
kube-system   cilium-gfwgl                                1/1     Running             0          3m2s
kube-system   cilium-operator-7d55b7dffc-2f45g            1/1     Running             0          3m4s
kube-system   ck-storage-rawfile-csi-controller-0         2/2     Running             0          3m5s
kube-system   ck-storage-rawfile-csi-node-tvkt2           4/4     Running             0          3m5s
kube-system   coredns-56d5ddcf86-6hfmg                    1/1     Running             0          3m5s
kube-system   metrics-server-8694c96fb7-bhq47             1/1     Running             0          3m5s
kube-system   task-2076ea3c-3d85-4339-8e8d-e5a9d664d79b   0/1     ImagePullBackOff    0          70s
kube-system   task-25d1ebec-e12c-4ddf-b9f7-e6161e71aac9   0/1     ErrImagePull        0          10s
kube-system   task-261e6d8e-9b44-4550-97b0-bba8c6483742   0/1     ErrImagePull        0          40s
kube-system   task-345c6cac-34d9-487e-b915-0783ccb8c8e9   0/1     ImagePullBackOff    0          80s
kube-system   task-3c7daca3-2970-4b66-b246-99e9590534c3   0/1     ImagePullBackOff    0          20s
kube-system   task-5b8893bd-9bf6-4f7d-adef-81fb16e0b2a3   0/1     ErrImagePull        0          60s
kube-system   task-72b630b1-a0cb-492c-88f8-5c229d01c119   0/1     ImagePullBackOff    0          90s
kube-system   task-7fe6b7b5-4d49-405f-8493-3a24924d0a7c   0/1     ErrImagePull        0          30s
kube-system   task-dcf0a00c-98e9-4b09-a54d-367e1a664627   0/1     ContainerCreating   0          0s
kube-system   task-fe25df5a-788e-4d34-9f24-e4c28ecbeab3   0/1     ImagePullBackOff    0          50s
```
**-> many tasks are created but with `ImagePullBackOff` or `ErrImagePull`**

```bash
$ sudo k8s kubectl describe -n kube-system pod/task-25d1ebec-e12c-4ddf-b9f7-e6161e71aac9
Name:             task-25d1ebec-e12c-4ddf-b9f7-e6161e71aac9
Namespace:        kube-system
Priority:         0
Service Account:  default
Node:             k8s-test/192.168.123.133
Start Time:       Mon, 07 Apr 2025 09:08:34 +0000
Labels:           <none>
Annotations:      <none>
Status:           Pending
IP:               10.1.0.145
IPs:
  IP:  10.1.0.145
Containers:
  task:
    Container ID:  
    Image:         ghcr.io/canonical/rawfile-localpv:None
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
    Args:
      
      python <<EOF
      import base64
      import pickle
      
      remote_fn = lambda fn: fn # FIXME: dirty hack
      call_data = pickle.loads(base64.b64decode(b'gASVVwIAAAAAAABdlChCAgIAAEByZW1vdGVfZm4KZGVmIGV4cGFuZF9yYXdmaWxlKHZvbHVtZV9pZCwgc2l6ZSk6CiAgICBpbXBvcnQgcmF3ZmlsZV91dGlsCgogICAgZnJvbSB1dGlsIGltcG9ydCBydW4KICAgIGZyb20gY29uc3RzIGltcG9ydCBSRVNPVVJDRV9FWEhBVVNURURfRVhJVF9DT0RFCgogICAgaW1nX2ZpbGUgPSByYXdmaWxlX3V0aWwuaW1nX2ZpbGUodm9sdW1lX2lkKQogICAgc2l6ZV9pbmMgPSBzaXplIC0gcmF3ZmlsZV91dGlsLm1ldGFkYXRhKHZvbHVtZV9pZClbInNpemUiXQogICAgaWYgc2l6ZV9pbmMgPD0gMDoKICAgICAgICByZXR1cm4KICAgIGlmIHJhd2ZpbGVfdXRpbC5nZXRfY2FwYWNpdHkoKSA8IHNpemVfaW5jOgogICAgICAgIGV4aXQoUkVTT1VSQ0VfRVhIQVVTVEVEX0VYSVRfQ09ERSkKCiAgICByYXdmaWxlX3V0aWwucGF0Y2hfbWV0YWRhdGEoCiAgICAgICAgdm9sdW1lX2lkLAogICAgICAgIHsic2l6ZSI6IHNpemV9LAogICAgKQogICAgcnVuKGYidHJ1bmNhdGUgLXMge3NpemV9IHtpbWdfZmlsZX0iKQqUKX2UKIwJdm9sdW1lX2lklIwocHZjLTQyNDU1NWQzLTE2YzEtNGE1ZS1iZDNmLTMxODEyNjhlMDI0NJSMBHNpemWUigUAAACAAHVlLg=='))


...


Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  100s                default-scheduler  Successfully assigned kube-system/task-25d1ebec-e12c-4ddf-b9f7-e6161e71aac9 to k8s-test
  Normal   Pulling    14s (x4 over 100s)  kubelet            Pulling image "ghcr.io/canonical/rawfile-localpv:None"
  Warning  Failed     14s (x4 over 100s)  kubelet            Failed to pull image "ghcr.io/canonical/rawfile-localpv:None": rpc error: code = NotFound desc = failed to pull and unpack image "ghcr.io/canonical/rawfile-localpv:None": failed to resolve reference "ghcr.io/canonical/rawfile-localpv:None": ghcr.io/canonical/rawfile-localpv:None: not found
  Warning  Failed     14s (x4 over 100s)  kubelet            Error: ErrImagePull
  Normal   BackOff    1s (x5 over 100s)   kubelet            Back-off pulling image "ghcr.io/canonical/rawfile-localpv:None"
  Warning  Failed     1s (x5 over 100s)   kubelet            Error: ImagePullBackOff
```

**-> It tries to pull "ghcr.io/canonical/rawfile-localpv:None"**

### System information

[inspection-report-20250407_091155.tar.gz](https://github.com/user-attachments/files/19629378/inspection-report-20250407_091155.tar.gz)

**Comment by nobuto-m** [comment]
I didn't have enough time to follow the logic to determine the image tag. Some of the Helm values have `ghcr.io/canonical/rawfile-localpv:0.8.0-ck4` as expected, but "env" only has `IMAGE_REPOSITORY=ghcr.io/canonical/rawfile-localpv` but no IMAGE_TAG possibly due to the upstream looking for a `-ci` tag. Not sure if it's the root cause at this point though.
https://github.com/canonical/rawfile-localpv/blob/46512a32284c7610a277945b7505060538b76159/deploy/charts/rawfile-csi/templates/01-controller-plugin.yaml#L59-L62

```yaml
# Source: rawfile-csi/templates/01-controller-plugin.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ck-storage-rawfile-csi-controller
spec:
  replicas: 1
  serviceName: ck-storage-rawfile-csi
  selector:
    matchLabels: &selectorLabels
      app.kubernetes.io/name: rawfile-csi
      app.kubernetes.io/instance: ck-storage
      component: controller
  template:
    metadata:
      labels: *selectorLabels
    spec:
      serviceAccount: ck-storage-rawfile-csi-driver
      priorityClassName: system-cluster-critical
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: Equal
          value: "true"
          effect: NoSchedule
        - key: "node-role.kubernetes.io/control-plane"
          operator: Equal
          value: "true"
          effect: NoSchedule
      volumes:
        - name: socket-dir
          emptyDir: {}
      containers:
        - name: csi-driver
          image: "ghcr.io/canonical/rawfile-localpv:0.8.0-ck4"
          imagePullPolicy: Always
          args:
          - --args
          - rawfile
          - csi-driver
          - --disable-metrics
          env:
            - name: PROVISIONER_NAME
              value: "rawfile.csi.openebs.io"
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: IMAGE_REPOSITORY
              value: "ghcr.io/canonical/rawfile-localpv"
```

**Comment by nobuto-m** [comment]
Looks like the upstream helm chart (https://github.com/openebs/rawfile-localpv/tree/develop/deploy/charts/rawfile-csi) can complete the resize.

```bash
$ kubectl get pv,pvc
NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM             STORAGECLASS      VOLUMEATTRIBUTESCLASS   REASON   AGE
persistentvolume/pvc-2844d93c-540d-4ebe-a66b-ae92e54f7d53   2Gi        RWO            Delete           Bound    default/myclaim   rawfile-localpv   <unset>                          10m

NAME                            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      VOLUMEATTRIBUTESCLASS   AGE
persistentvolumeclaim/myclaim   Bound    pvc-2844d93c-540d-4ebe-a66b-ae92e54f7d53   2Gi        RWO            rawfile-localpv   <unset>                 13m
```

```yaml
$ kubectl describe pvc
Name:          myclaim
Namespace:     default
StorageClass:  rawfile-localpv
Status:        Bound
Volume:        pvc-2844d93c-540d-4ebe-a66b-ae92e54f7d53
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: rawfile.csi.openebs.io
               volume.kubernetes.io/selected-node: kubeadm-test
               volume.kubernetes.io/storage-provisioner: rawfile.csi.openebs.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      2Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       storage-writer-pod
Events:
  Type    Reason                      Age                From                                                                                Message
  ----    ------                      ----               ----                                                                                -------
  Normal  FailedBinding               12m (x9 over 14m)  persistentvolume-controller                                                         no persistent volumes available for this claim and no storage class is set
  Normal  WaitForPodScheduled         11m (x5 over 12m)  persistentvolume-controller                                                         waiting for pod storage-writer-pod to be scheduled
  Normal  WaitForFirstConsumer        11m                persistentvolume-controller                                                         waiting for first consumer to be created before binding
  Normal  ExternalProvisioning        11m                persistentvolume-controller                                                         Waiting for a volume to be created either by the external provisioner 'rawfile.csi.openebs.io' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
  Normal  Provisioning                11m                rawfile.csi.openebs.io_rawfile-csi-node-6dzhq_42293d1c-9202-43a5-a4cf-df308074c360  External provisioner is provisioning volume for claim "default/myclaim"
  Normal  ProvisioningSucceeded       11m                rawfile.csi.openebs.io_rawfile-csi-node-6dzhq_42293d1c-9202-43a5-a4cf-df308074c360  Successfully provisioned volume pvc-2844d93c-540d-4ebe-a66b-ae92e54f7d53
  Normal  ExternalExpanding           3m11s              volume_expand                                                                       waiting for an external controller to expand this PVC
  Normal  Resizing                    3m11s              external-resizer rawfile.csi.openebs.io                                             External resizer is resizing volume pvc-2844d93c-540d-4ebe-a66b-ae92e54f7d53
  Normal  FileSystemResizeRequired    3m5s               external-resizer rawfile.csi.openebs.io                                             Require file system resize of volume on node
  Normal  FileSystemResizeSuccessful  117s               kubelet                                                                             MountVolume.NodeExpandVolume succeeded for volume "pvc-2844d93c-540d-4ebe-a66b-ae92e54f7d53" kubeadm-test
```
