### ISSUE TITLE
Passing node labels in kubelet args replace all default control plane labels

### ISSUE THREAD

**Issue by kpiyush17** [canonical/k8s-snap#1402]
### Summary

Hi,

I am adding a custom node label to `extra-node-kubelet-args`:
```
extra-node-kubelet-args:
    --feature-gates: RotateKubeletServerCertificate=true
    --node-labels: hello=world
``` 

Doing this replaces all the default control plane labels, which affects the role of the node:
```
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      hello: world
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: piyush
      kubernetes.io/os: linux
```

```
root@piyush:~# k8s kubectl get nodes
NAME     STATUS     ROLES    AGE   VERSION
piyush   NotReady   <none>   19s   v1.32.3
root@piyush:~#
```

Thanks

### What Should Happen Instead?

Custom labels should get appended to the node.

### Reproduction Steps

Bootstrap a node with the following in the config:

```
extra-node-kubelet-args:
    --node-labels: hello=world
```

### System information

OS: Ubuntu 22.04 
K8s: 1.32 LTS
