### ISSUE TITLE
Docs: CAPI / Reference / Configs missing spaces in bootstrapConfig example

### ISSUE THREAD

**Issue by gustavosr98** [canonical/k8s-snap#1405]
Doc: https://documentation.ubuntu.com/canonical-kubernetes/release-1.32/capi/reference/configs/#bootstrapconfig

Description: Based on [this other document](https://documentation.ubuntu.com/canonical-kubernetes/release-1.32/snap/reference/config-files/bootstrap-config/#containerd-base-dir)
network, dns, ingress, etc should be bellow cluster-config and not at the same level as it

The document at the moment
```yaml
spec:
  bootstrapConfig:
    content: |
      cluster-config:
      network:
          enabled: true
      dns:
          enabled: true
          cluster-domain: cluster.local
      ingress:
          enabled: true
      load-balancer:
          enabled: true
```

How it should look like
```yaml
spec:
  bootstrapConfig:
    content: |
      cluster-config:
        network:
          enabled: true
        dns:
          enabled: true
          cluster-domain: cluster.local
        ingress:
          enabled: true
        load-balancer:
          enabled: true
```

---
Document: capi/reference/configs.md
