### ISSUE TITLE
metallb exposed services not reachable from co-located LXC container on same bridge

### ISSUE THREAD

**Issue by baycarbone** [canonical/k8s-snap#1481]
### Summary

When k8s is deployed in a cluster using a Linux bridge as cilium and load-balancer interface; if LXD is used to deploy containers connected to the same Linux bridge, metalLB exposed services are not reachable from within the LXC containers (timeout trying to connect).
If LXC containers are deployed on a LXD managed bridge instead e.g. lxdbr0, it works fine. If a VM is deployed using LXD, connected to the Linux bridge, it also works fine.

### What Should Happen Instead?

Connectivity from within a LXC container connected to a Linux bridge used for k8s, to metalLB exposed services inside the k8s cluster should be working.

### Reproduction Steps

1. deploy a machine and configure a Linux bridge
2. install and initialize lxd
3. deploy k8s using the following boostrap config file
```
cluster-config:
  network:
    enabled: true
  dns:
    enabled: true
  local-storage:
    enabled: false
  load-balancer:
    enabled: true
    cidrs:
    - 172.27.41.200-172.27.41.205
    l2-mode: true
    l2-interfaces:
    - br0
  annotations:
    k8sd/v1alpha1/cilium/devices: br0
    k8sd/v1alpha1/cilium/direct-routing-device: br0
```
3. deploy 2 more machines and configure a Linux bridge
4. make the new machines join the k8s cluster
5. deploy a pod with a LoadBalancer type service
6. deploy a LXC container using LXD, connected to the Linux bridge (e.g. `nictype: bridged` and `parent: <Linux bridge name>`
7. try to access the service from within the LXC container

### System information

Ubuntu 24.04, k8s v1.32.3, lxd 5.21.3-c5ae129
