### ISSUE TITLE
No documentation about K8s API endpoint high-availability

### ISSUE THREAD

**Issue by nobuto-m** [canonical/k8s-snap#1499]
### Summary

Previously we had some documentation around K8s API endpoint HA (High Availability) at least for the charmed deployment:
- https://ubuntu.com/kubernetes/charmed-k8s/docs/high-availability
- https://ubuntu.com/kubernetes/charmed-k8s/docs/keepalived
- https://ubuntu.com/kubernetes/charmed-k8s/docs/hacluster

However, in the new project, I don't see any mention about those parts of HA. There is a page in the snap section but it doesn't cover user-facing K8s API endpoint.
https://documentation.ubuntu.com/canonical-kubernetes/release-1.32/snap/explanation/high-availability/

### What Should Happen Instead?

Official procedure to achieve K8s API endpoint HA should be in the documentation.

### Reproduction Steps

N/A

### System information

N/A

### Can you suggest a fix?

Fwiw, the following architecture is working with keepalived still. So it's more of capturing our official stance instead of developing something new.

```yaml
default-base: ubuntu@24.04
applications:
  k8s:
    charm: k8s
    channel: 1.32/stable
    num_units: 3
    to:
    - "0"
    - "1"
    - "2"
    options:
      kube-apiserver-extra-sans: 10.0.9.21
      load-balancer-enabled: true
      load-balancer-l2-mode: true
      load-balancer-cidrs: 10.0.9.31-10.0.9.40
  keepalived:
    charm: keepalived
    channel: 1.32/stable
    options:
      port: 6443
      virtual_ip: 10.0.9.21
machines:
  "0":
    constraints: arch=amd64 cpu-cores=4 mem=16384 root-disk=32768 virt-type=virtual-machine
  "1":
    constraints: arch=amd64 cpu-cores=4 mem=16384 root-disk=32768 virt-type=virtual-machine
  "2":
    constraints: arch=amd64 cpu-cores=4 mem=16384 root-disk=32768 virt-type=virtual-machine
relations:
- - keepalived:juju-info
  - k8s:juju-info
```
